### ISSUE TITLE
 Could not find artifact org.mybatis.caches:mybatis-redis:jar:1.0.0-SNAPSHOT when using Maven

### ISSUE THREAD

**Issue by edwinkun** [mybatis/redis-cache#1]
trying to use redis via maven,

```
 <dependency>
    <groupId>org.mybatis.caches</groupId>
    <artifactId>mybatis-redis</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </dependency>
```
got this error,
 ``` 
Could not find artifact org.mybatis.caches:mybatis-redis:jar:1.0.0-SNAPSHOT -> [Help 1]
 ``` 

im using this example,
 ``` 
http://mybatis.github.io/redis-cache/index.html
 ``` 

do you have any idea what maven repositories should i use?
thank you.

**Comment by hazendaz** [comment]
Snapshot wouldn't normally be released.

--- Original Message ---

**Comment by emacarron** [comment]
Yeah! This was issue #1!! :)

The project is only in a very early inception phase. We need people to use it, discuss on it and ... probably fix things. 

Snapshots are usually published to https://oss.sonatype.org/content/repositories/snapshots/org/mybatis/caches/ so you can point to this repo to use the code. Please, tell us about it!

@harawata Iwao.... I have replicated the configuration you have made for other repos but the deployment to sonatype is giving me an Unauthorized. Can you please have a look?

**Comment by harawata** [comment]
Hi guys!
The snapshot should be available now :-)

The  'travis encrypt' command needs to be executed in each project repo even if the username/password are the same because the encryption key is different for each project.

**Comment by emacarron** [comment]
Thank you very much Iwao.

**Comment by emacarron** [comment]
Hi @edwinkun I have just sent a beta1 version to maven central so you will be able to find it easily.

**Comment by edwinkun** [comment]
thanks @emacarron , i really appreciate it
