### ISSUE TITLE
beta3?

### ISSUE THREAD

**Issue by raupachz** [mybatis/redis-cache#101]
Hi there,

are there any updates on redis-cache? Anything needed to help out? 

Last version is from 2015 and there have been many updates in Jedis and MyBatis. 

Thank you for your time!

**Comment by harawata** [comment]
Hello @raupachz ,

Does the latest beta3 snapshot work without a problem?
If yes, I can do the release.

**Comment by raupachz** [comment]
Does work on my machine. Can tell you more once it runs in production.

**Comment by hazendaz** [comment]
plan to release soon, closing ticket for now to clear out issues.
