### ISSUE TITLE
KryoSerializer  is more space consuming than JDKSerializer?

### ISSUE THREAD

**Issue by a1364533187** [mybatis/redis-cache#118]
In class `KryoSerializer`,  I see the comments about `SerializeUtil with Kryo, which is faster and more space consuming.`,   but when I read this article `https://www.shenyanchao.cn/blog/2019/02/13/redis-serializer/`,   it looks like  `KryoSerializer` is  faster and less space consuming. 

![se](https://user-images.githubusercontent.com/12780186/115528476-a75b4b80-a2c4-11eb-9bbc-b67b8f8f59cb.png)
article reference: [https://www.shenyanchao.cn/blog/2019/02/13/redis-serializer/](url)

**Comment by hazendaz** [comment]
sorry didn't see this previously as this project isn't monitored that closely, you are correct, I've fixed it to state 'less space consuming'.
