### ISSUE TITLE
What's the status of this project?

### ISSUE THREAD

**Issue by adrianboimvaser** [mybatis/redis-cache#134]
Last release in Maven central repository was 28-Dec-2015.
How can I contribute to make it move forward?

**Comment by harawata** [comment]
Hello @adrianboimvaser ,

As there is no active maintainer, this project mostly relies on user' contributions.
Is the latest beta-3 snapshot working without a problem?
If it is, I can release beta-3.

**Comment by hazendaz** [comment]
closing as answered, will be released in near future.
