### ISSUE TITLE
If you use AliCloudDB for Redis,set the clientName to be empty.

### ISSUE THREAD

**Issue by songjiesdnu** [mybatis/redis-cache#20]
I used  AliCloudDB for Redis as my redis, and then occured an error, notice me that the command "client" was not supported.The i checked the source code, and found that, in the class RedisCache, when new a JedisPool, it set the clientName.But  AliCloudDB for Redis does not support command "client" yet.

The solution is set the clientName to be empty in you redis config file.

**Comment by hazendaz** [comment]
@songjiesdnu Is this still an issue and if so, can you submit a PR with instructions on the README?

**Comment by harawata** [comment]
No response.
FYI, I couldn't find anything about AliCloudDB on Google.
