### ISSUE TITLE
cache setting [flushInterval] not work

### ISSUE THREAD

**Issue by summer9989** [mybatis/redis-cache#31]
I use flushInterval like this:

`<mapper namespace="cn.com.xxxxx.dao.mapper.TestMapper">
	<cache type="org.mybatis.caches.redis.RedisCache" flushInterval="2000"/>
...
`

after more than 2 seconds,I use this query again,but I just see information like this(in console):

org.apache.ibatis.cache.decorators.LoggingCache:62 - Cache Hit Ratio [cn.com.chengyisheng.dao.mapper.TestMapper]: 0.875

It means this query use cache result again.

why?  How to use flushInterval

**Comment by emacarron** [comment]
User the mail list please

**Comment by summer9989** [comment]
@emacarron   sorry,what do you mean?

**Comment by harawata** [comment]
I've added `timeout` property (see #52 ).
It would be great if you guys could test it with the latest snapshot.
