### ISSUE TITLE
Is this framework support SQL's join?

### ISSUE THREAD

**Issue by shangdiyisi** [mybatis/redis-cache#34]
Is this framework support SQL's join?

**Comment by h3adache** [comment]
@shangdiyisi is this question about if mybatis supports sql joins? mybatis supports any jdbc sql statement so yes. Please use the mailing list (http://groups.google.com/group/mybatis-user) and the documentation (http://www.mybatis.org/mybatis-3) if you have other questions.

**Comment by shangdiyisi** [comment]
Actually, what i want to ask if mybatis-redis support sql joins? I know mybatis-redis will evict all cache of a mysql table when i modify the table's data. If only modify one table's data, will mybatis-redis evict the two table's cache which used join statement?
