### ISSUE TITLE
Property name in redis.properties collided with jdbc.properties.

### ISSUE THREAD

**Issue by anyonghua** [mybatis/redis-cache#38]
Hello

I found that in redis.properties the property names must be **host,port,password**, otherwise mybatis will config the redis with the default value .

For example, below is my redis.properties

```
redis.host=192.168.1.10
redis.port=6379
redis.password=
redis.maxIdle=100
redis.maxActive=300
redis.maxWait=1000
redis.testOnBorrow=true
redis.timeout=100000
```

MyBatis cannot find host,port,password (and ingore the properties maxIdle,maxActive...),but set the host with default value `localhost` and I had got connection refused error.
I must define 

```
host=192.168.1.10
port=6379
password=
```

In my project, there was also a property password  in jdbc.properties, so...I must change the jdbc property name and modify dbcp config in spring config file carefully.

This problem confused me quite a time, it seems the redis server was not setup corrected at first...finally I found the truth above !

I wrote this issue for hoping others to avoid the same problem!

**Comment by hazendaz** [comment]
@harawata This project is still beta, I like taking this one and refactoring it to prefix redis.  What do you think?

**Comment by harawata** [comment]
@hazendaz +1 to add redis prefix.
