### ISSUE TITLE
when redis server down 

### ISSUE THREAD

**Issue by iarwen** [mybatis/redis-cache#39]
if redis server down,i want direct query from db and not throw exception, how  can i config?

**Comment by smoner** [comment]
maybe ,you can catch the exception ,don't throw   and  direct  query  from  db

**Comment by mahaoran** [comment]
No follow up?

**Comment by sunpe** [comment]
I think should add try-catch to RedisCallback.doWithRedis() to avoid system error. But it's need independent monitor to monitoring reids and mysql.

**Comment by hazendaz** [comment]
closing as old and not sure this was intended here as question on redis.
