### ISSUE TITLE
profile & jedis update

### ISSUE THREAD

**Issue by liuanxin** [mybatis/redis-cache#50]
How to Adaptation environment? like this

dev read redis-dev.properties
test read redis-test.properties
prod read redis-prod.properties

Or, I'm use spring boot, use the profiles, how to read environment in `org.springframework.boot.autoconfigure.data.redis.RedisProperties` ?

And, If use the new jedis version(2.9.0)
```java
pool = new JedisPool(...)
```
was error...

@hazendaz

**Comment by hazendaz** [comment]
@liuanxin Yes looks like we have a bug with 2.9.x.  When I added code to support 2.9.x all I really did was allow null in new ssl values.  We are looking at this and will try to get fixed as soon as possible.

**Comment by 2016flyinbed** [comment]
@hazendaz hi!  i meet the same problem, please help to fix it as soon as possible, think you very much

**Comment by harawata** [comment]
1.0.0-beta3 will support Redis 2.9.x.
Please test the snapshot version and report any issue you find before the final release (see https://github.com/mybatis/redis-cache/issues/67#issuecomment-411490866).

Regarding the per-environment configuration, you can pass the property file's classpath via a system property named "redis.properties.filename".
I'll close this issue, but please let me know if it's not what you are looking for.

**Comment by liuanxin** [comment]
I add a project for this : https://github.com/liuanxin/mybatis-redis-cache

get Spring's redisTemplate to operate redis, not jedis, if redis can't connection, then go with db.
