### ISSUE TITLE
version error

### ISSUE THREAD

**Issue by LuckyTerry** [mybatis/redis-cache#67]
The src of the version 1.0.0-beta2 from maven are different from those from github.

especially, the constructor of RedisCache, as follow:

pool = new JedisPool(redisConfig, redisConfig.getHost(), redisConfig.getPort(),
			redisConfig.getConnectionTimeout(), redisConfig.getSoTimeout(), redisConfig.getPassword(),
			redisConfig.getDatabase(), redisConfig.getClientName());

which is not avaliable constructor of JedisPool of version 2.9.0...

or, is there anything i misunderstood?

**Comment by harawata** [comment]
1.0.0-beta2 was compiled against Jedis-2.8.0.
Please try 1.0.0-beta3-SNAPSHOT.

If you are using Maven, you may need to add a snapshot repository to your pom.xml.
https://github.com/mybatis/mybatis-3/wiki/Maven#snapshot
And the binary is here.
https://oss.sonatype.org/content/repositories/snapshots/org/mybatis/caches/mybatis-redis/1.0.0-beta3-SNAPSHOT/

**Comment by LuckyTerry** [comment]
Thanks a lot.
