### ISSUE TITLE
How to use with spring

### ISSUE THREAD

**Issue by BigBrotherLee** [mybatis/redis-cache#72]
how to write spring configration，Conflict with spring-data-redis?
thank you

**Comment by shootercheng** [comment]
demo  https://github.com/shootercheng/redis-cache-spring

**Comment by shootercheng** [comment]
> how to write spring configration，Conflict with spring-data-redis?
> thank you
demo https://github.com/shootercheng/redis-cache-spring

**Comment by hazendaz** [comment]
answered, closing issue.
